name: Solar System Workflow

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - 'feature/*'

jobs:
  unit-testing:
    name: Unit Testing
    services:
      mongo-db:
        image: siddharth67/mongo-db:non-prod
        ports:
          - 27017:27017
    env:
      MONGO_URI: 'mongodb+srv://localhost:27017/superData'
      MONGO_USERNAME: non-prod-user
      MONGO_PASSWORD: non-prod-password
    strategy:
      matrix:
        nodejs_version: [18, 20]
        operating_system: [ubuntu-latest, macos-latest]
        exclude:
        - nodejs_version: 18
          operating_system: macos-latest
    runs-on: ${{ matrix.operating_system }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Setup NodeJS Version - ${{ matrix.nodejs_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.nodejs_version }}
    - name: Cache NPM dependencies
      uses: actions/cache@v4
      with:
        path: node_module
        key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json')}}
    - name: Install Dependencies
      run: npm install
    - name: Unit Testing
      id: nodejs-unit-testing-step
      run: npm test
    - name: Archive Test Result
      if: steps.nodejs-unit-testing-step.outcome == 'failure' || steps.nodejs-unit-testing-step.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: Mocha-Test-Result-${{ matrix.operating_system }}-${{ matrix.nodejs_version }}
        path: test-results.xml
 

 
